version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: "logs/app.log"  # Tên file log cơ bản
    encoding: utf-8
    when: midnight
    backupCount: 7
loggers:
  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
